### PR TITLE
Blank/Active Stones

### PR DESCRIPTION
**Pull request by aravol**
Differentiated Blank stones from active ones, allowing blank stones to be more easily stacked and simplifying activation/usage code

### CODE REVIEW

**Comment by Vanhal** [comment]
I haven't read all the code for this yet but is this not going to erase any already marked stones?

**Comment by aravol** [comment]
This continues use to the same item classes for marked stones, so it shouldn't erase them, However, any unmarked stones will be rendered useless and have to recrafted, since they'll now register as "active" with no destination.

I'll run a quick test to be absolutely sure.

**Comment by aravol** [comment]
Confirmed, marked stones remain and continue function when upgrading (or downgrading!) to/from these changes.

**Comment by aravol** [comment]
Couple more changes, which interestingly just got pegged onto this pull request as part of the same. Attempted to make Recall Stones use Damage Bar, but it looked absolutely terrible with stacked stones, since damage bars are printed in front of stack sizes.

**Pull request merged**
